### ISSUE TITLE
关于瓦片生成问题，babylonjs

### ISSUE THREAD

**Issue by Happy0Ending** [sxguojf/three-tile-example#1]
我是babylonjs的开发人员，很高兴能看到这个项目，最近刚刚开始研究gis，我现在有几个问题想请教一下大佬，
1、下图下钻一个大的地图瓦片，我观察到一个瓦片下钻一级会生成4个小的下级地图瓦片，项目中是使用了立方体网格生成4个新的网格嘛？还是利用下级的4张地图贴片组合成一张重新贴上去。
2、three-tile是开源吗？近期有计划做babylonjs版本的计划吗？以及商业引用是否收费问题。

**Comment by sxguojf** [comment]
1、地图放大时，会根据摄像机与瓦片距离，生成4个下一级新瓦片，替换原有瓦片，不是贴在原有网格上。
2、three-tile计划开源，但目前还不够成熟，待进行一次大重构后开源，无收费计划。
3、考虑过做babylonjs和unity3d版，但这俩应用多为游戏开发，估计没有多少gis应用需求。

**Comment by 497983606** [comment]
mark， 开源后 api wiki 我来
