### ISSUE TITLE
请教一个threejs 地图的问题

### ISSUE THREAD

**Issue by FengFengmomo** [sxguojf/three-tile-example#11]
使用geometry.addGroup(0, Infinity, i); 加载多个材质的时候帧率会变慢是因为什么呢？
如果只使用一个材质不设置group则没有问题。

**Comment by sxguojf** [comment]
> 使用geometry.addGroup(0, Infinity, i); 加载多个材质的时候帧率会变慢是因为什么呢？ 如果只使用一个材质不设置group则没有问题。

你是在three-tile里使用？three-tile多个影像图时使用的是多重材质，但好像对速度没有多大影响。

使用多重纹理，必要要加geometry.addGroup(0, Infinity, i)，一个材质不用加，多重材质应该不会明显影响fps，除非你另加的材质很复杂。

three-tile中，图层叠加使用自定义着色器、Canvas、多重材质都实现过，三者速度没有明显区别，目前使用多重材质。

**Comment by sxguojf** [comment]
可以试试：geometry.addGroup(0,mesh.geometry.index.count,i); 但这个应该不影响速度

**Comment by FengFengmomo** [comment]
已经解决了，原因是我在初始化mesh的时候使用的是单个materials，但我在加载材质的时候是多个，因为冲突才导致的整体速度变慢，修改掉这个冲突以后就好了。非常感谢大佬提供的解说。
