### ISSUE TITLE
is:issue is:open 大佬，我已重点关注，坐等开源

### ISSUE THREAD

**Issue by yangyangzuo** [sxguojf/three-tile-example#2]

**Comment by sxguojf** [comment]
迫于生计，实在没时间写代码，开源得往后拖拖

**Comment by yangyangzuo** [comment]
代码我已经反编译了一版，但是还有一些问题，如果可能的话，可以把现有的开源，如果开源的话，大家就好参与进来了

**Comment by 497983606** [comment]
插个眼，我准备写一个呢，坐等开源一起把地理计算和地球模式搞出来，还要什么 cesium~~~

**Comment by 497983606** [comment]
同为西安人，加个微信吧铁子 SXNfSm9zaHVh  wxid base64了

**Comment by minemine-m** [comment]
插眼

**Comment by sxguojf** [comment]
源码已开放：https://github.com/sxguojf/three-tile

**Comment by yangyangzuo** [comment]
第一时间收到！
