### ISSUE TITLE
瓦片的隐藏疑惑

### ISSUE THREAD

**Issue by yangyangzuo** [sxguojf/three-tile-example#3]
![微信图片_20240322180130](https://github.com/sxguojf/three-tile-example/assets/11265362/4fa25883-9f20-4909-8c1d-df2d0b823fa7)

tile.js中有这样的代码，为什么瓦片的隐藏判断条件中要加上这样一个要求
当瓦片是父瓦片的左下角那个瓦片的时候,才有可能会被隐藏

**Comment by sxguojf** [comment]
你研究的够深入。因为瓦片是按四叉树组织的，一个节点有四个子瓦片，缩小时四块瓦片只要有一块满足条件就全隐藏了，不用全部判断，这里选了左下角的，选0-3任意一块都可以。不过这块逻辑有些问题，有时瓦片会出现抖动，新版的已经全部重写了。

**Comment by yangyangzuo** [comment]
好的，多谢解答，我这边再研究一下，后续可能还有问题请教，希望不吝赐教
