### ISSUE TITLE
给模型设置材质贴图，始终都是黑色，同样的材质贴图代码，在three最初始场景中能够进行贴图成功，在three-tile场景中贴图不成功。什么原因？

### ISSUE THREAD

**Issue by zenghaiy** [sxguojf/three-tile-example#8]
![Snipaste_2024-06-30_18-22-13](https://github.com/sxguojf/three-tile-example/assets/88429575/88ec43a8-62b0-4d2e-af0b-0dd8cf21c4ee)

**Comment by sxguojf** [comment]
![image](https://github.com/sxguojf/three-tile-example/assets/67039275/d1a046ca-187c-48d7-a474-213e222098b0)
![image](https://github.com/sxguojf/three-tile-example/assets/67039275/c6d0893f-b2f6-423e-b427-de53f02b8672)

试了一下，添加模型贴图没有问题。是否是你的图片url不对？

**Comment by zenghaiy** [comment]
路径应该是没问题的，路径有问题会直接报错，Texture信息能够成功打印，但是当把Texture设置到模型的的map属性上后，模型始终都是黑色的。
![Snipaste_2024-07-01_09-42-09](https://github.com/sxguojf/three-tile-example/assets/88429575/1e5c22b5-6c42-4867-a4e3-38eadf6c45e9)
![Snipaste_2024-07-01_09-44-36](https://github.com/sxguojf/three-tile-example/assets/88429575/cddeefa5-fec7-43e9-8394-075bd8afc220)

**Comment by sxguojf** [comment]
three-tile仅是提供了一个地图Mesh，没有其它设置，不会影响你在场景中添加的其它模型。试试我贴的那段代码，直接用new TextureLoader().load("./test.jpg")加载纹理试试。

贴出你的this.loadTexture函数看看？

**Comment by zenghaiy** [comment]
解决了，我把three-tile和three的版本更新到你最新发布的版本就没问题了。
